/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'
import { Route as ApiOpenapiDotyamlRouteImport } from './routes/api/openapi[.]yaml'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminPracticeAreasIndexRouteImport } from './routes/admin/practice-areas/index'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin/blogs/index'
import { Route as ApiV1StatusRouteImport } from './routes/api/v1/status'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProjectsSlugRouteImport } from './routes/admin/projects/$slug'
import { Route as AdminPracticeAreasSlugRouteImport } from './routes/admin/practice-areas/$slug'
import { Route as AdminBlogsSlugRouteImport } from './routes/admin/blogs/$slug'

const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotyamlRoute = ApiOpenapiDotyamlRouteImport.update({
  id: '/api/openapi.yaml',
  path: '/api/openapi.yaml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPracticeAreasIndexRoute = AdminPracticeAreasIndexRouteImport.update({
  id: '/practice-areas/',
  path: '/practice-areas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiV1StatusRoute = ApiV1StatusRouteImport.update({
  id: '/api/v1/status',
  path: '/api/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsSlugRoute = AdminProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPracticeAreasSlugRoute = AdminPracticeAreasSlugRouteImport.update({
  id: '/practice-areas/$slug',
  path: '/practice-areas/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsSlugRoute = AdminBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/timeline': typeof TimelineRoute
  '/why-us': typeof WhyUsRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/api/openapi.yaml': typeof ApiOpenapiDotyamlRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/blogs/$slug': typeof AdminBlogsSlugRoute
  '/admin/practice-areas/$slug': typeof AdminPracticeAreasSlugRoute
  '/admin/projects/$slug': typeof AdminProjectsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/status': typeof ApiV1StatusRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/practice-areas/': typeof AdminPracticeAreasIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/timeline': typeof TimelineRoute
  '/why-us': typeof WhyUsRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/api/openapi.yaml': typeof ApiOpenapiDotyamlRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/blogs/$slug': typeof AdminBlogsSlugRoute
  '/admin/practice-areas/$slug': typeof AdminPracticeAreasSlugRoute
  '/admin/projects/$slug': typeof AdminProjectsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/status': typeof ApiV1StatusRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/practice-areas': typeof AdminPracticeAreasIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/timeline': typeof TimelineRoute
  '/why-us': typeof WhyUsRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/api/openapi.yaml': typeof ApiOpenapiDotyamlRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/blogs/$slug': typeof AdminBlogsSlugRoute
  '/admin/practice-areas/$slug': typeof AdminPracticeAreasSlugRoute
  '/admin/projects/$slug': typeof AdminProjectsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/status': typeof ApiV1StatusRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/practice-areas/': typeof AdminPracticeAreasIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/openapi.json'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/timeline'
    | '/why-us'
    | '/.well-known/api-catalog'
    | '/admin/login'
    | '/api/$'
    | '/api/openapi.yaml'
    | '/blogs/$slug'
    | '/projects/$slug'
    | '/resources/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/blogs/'
    | '/projects/'
    | '/services/'
    | '/admin/blogs/$slug'
    | '/admin/practice-areas/$slug'
    | '/admin/projects/$slug'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1/status'
    | '/admin/blogs/'
    | '/admin/practice-areas/'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/openapi.json'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/timeline'
    | '/why-us'
    | '/.well-known/api-catalog'
    | '/admin/login'
    | '/api/$'
    | '/api/openapi.yaml'
    | '/blogs/$slug'
    | '/projects/$slug'
    | '/resources/$slug'
    | '/services/$slug'
    | '/admin'
    | '/blogs'
    | '/projects'
    | '/services'
    | '/admin/blogs/$slug'
    | '/admin/practice-areas/$slug'
    | '/admin/projects/$slug'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1/status'
    | '/admin/blogs'
    | '/admin/practice-areas'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/openapi.json'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/timeline'
    | '/why-us'
    | '/.well-known/api-catalog'
    | '/admin/login'
    | '/api/$'
    | '/api/openapi.yaml'
    | '/blogs/$slug'
    | '/projects/$slug'
    | '/resources/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/blogs/'
    | '/projects/'
    | '/services/'
    | '/admin/blogs/$slug'
    | '/admin/practice-areas/$slug'
    | '/admin/projects/$slug'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1/status'
    | '/admin/blogs/'
    | '/admin/practice-areas/'
    | '/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TimelineRoute: typeof TimelineRoute
  WhyUsRoute: typeof WhyUsRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiOpenapiDotyamlRoute: typeof ApiOpenapiDotyamlRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1StatusRoute: typeof ApiV1StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.yaml': {
      id: '/api/openapi.yaml'
      path: '/api/openapi.yaml'
      fullPath: '/api/openapi.yaml'
      preLoaderRoute: typeof ApiOpenapiDotyamlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/practice-areas/': {
      id: '/admin/practice-areas/'
      path: '/practice-areas'
      fullPath: '/admin/practice-areas/'
      preLoaderRoute: typeof AdminPracticeAreasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/v1/status': {
      id: '/api/v1/status'
      path: '/api/v1/status'
      fullPath: '/api/v1/status'
      preLoaderRoute: typeof ApiV1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$slug': {
      id: '/admin/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/admin/projects/$slug'
      preLoaderRoute: typeof AdminProjectsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/practice-areas/$slug': {
      id: '/admin/practice-areas/$slug'
      path: '/practice-areas/$slug'
      fullPath: '/admin/practice-areas/$slug'
      preLoaderRoute: typeof AdminPracticeAreasSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/$slug': {
      id: '/admin/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/admin/blogs/$slug'
      preLoaderRoute: typeof AdminBlogsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsSlugRoute: typeof AdminBlogsSlugRoute
  AdminPracticeAreasSlugRoute: typeof AdminPracticeAreasSlugRoute
  AdminProjectsSlugRoute: typeof AdminProjectsSlugRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
  AdminPracticeAreasIndexRoute: typeof AdminPracticeAreasIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsSlugRoute: AdminBlogsSlugRoute,
  AdminPracticeAreasSlugRoute: AdminPracticeAreasSlugRoute,
  AdminProjectsSlugRoute: AdminProjectsSlugRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
  AdminPracticeAreasIndexRoute: AdminPracticeAreasIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TimelineRoute: TimelineRoute,
  WhyUsRoute: WhyUsRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiOpenapiDotyamlRoute: ApiOpenapiDotyamlRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1StatusRoute: ApiV1StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
